services:
  - type: worker
    name: veribot
    runtime: docker
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: VIRUSTOTAL_KEY
        sync: false
      - key: ANTHROPIC_KEY
        sync: false
      - key: URLSCAN_KEY
        sync: false
      - key: GOOGLE_SAFE_BROWSING_KEY
        sync: false
      - key: PHISHTANK_KEY
        sync: false
      - key: ABUSEIPDB_KEY
        sync: false
